import store from "@/lib/redux/store";
import type { Metadata } from "next";
import Providers from "@/lib/redux/providers";

export const metadata: Metadata = {
  title: "Fleet Management System",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </Providers>
  );
}
