import type { Metadata } from "next";
import Topbar from "../components/topbar/Topbar";
import Providers from "@/lib/redux/providers";

export const metadata: Metadata = {
  title: "Fleet Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Topbar />
          <div style={{ marginTop: 80 }}>
            {children}
          </div>
        </body>
      </html>
    </Providers>
  );
}
